### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by laojin** [ZJUguquan/FengjrCompetitionPrelim#1]
OSError: dlopen(/usr/local/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/8/libgomp.1.dylib
  Referenced from: /usr/local/lib/python3.7/site-packages/lightgbm/lib_lightgbm.so
  Reason: image not found

**Comment by ZJUguquan** [comment]
@laojin 这应该是你lightgbm这个包没有正确安装

**Comment by laojin** [comment]
pip3 list
Package         Version
--------------- -------
lightgbm        2.2.0  
numpy           1.15.1 
pandas          0.23.4 
pip             18.0   
python-dateutil 2.7.3  
pytz            2018.5 
scikit-learn    0.19.2 
scipy           1.1.0  
setuptools      40.4.1 
six             1.11.0 
wheel           0.31.1

**Comment by laojin** [comment]
/usr/local/lib/python3.7/site-packages/lightgbm/__init__.py:45: FutureWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS will be built by the Apple Clang compiler.
This means that in case of installing LightGBM from PyPI via the ``pip install lightgbm`` command, you won't need to install the gcc compiler anymore.
Instead of that, you'll need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.
You can install the OpenMP library by the following command: ``brew install libomp``.
  "You can install the OpenMP library by the following command: ``brew install libomp``.", FutureWarning)
Traceback (most recent call last):
  File "model.py", line 231, in <module>
    train1_r4, train2_r4 = getTrainData(r"./data/round4/")
  File "model.py", line 73, in getTrainData
    data = readRoundFiles(round_dir)
  File "model.py", line 21, in readRoundFiles
    data = pd.concat([readDayFile(f) for f in file_list]).reset_index(drop=True)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "/usr/local/lib/python3.7/site-packages/pandas/core/reshape/concat.py", line 259, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate

这些是什么意思

**Comment by fangbaolin** [comment]
系统找不到指定的路径：./data/round4?????????????????????????

**Comment by ZJUguquan** [comment]
> 系统找不到指定的路径：./data/round4?????????????????????????

数据要到比赛官网去下载解压的
